import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";
import type { CacheEntry, ComponentContext } from "./types";

interface CacheData {
  [hash: string]: CacheEntry;
}

const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
const MAX_CACHE_ENTRIES = 100;

// Bump this whenever the generation prompt/logic changes in a way that should
// invalidate previously-cached mocks. It is folded into the cache key so old
// entries (generated by a prior prompt) become misses and get regenerated.
const CACHE_VERSION = "2";

export class PreviewCache {
  private cachePath: string;

  constructor(workspaceRoot: string) {
    this.cachePath = path.join(workspaceRoot, ".component-preview", "cache.json");
  }

  /**
   * Compute a hash of the component file + all dependency files.
   * This serves as the cache key - if any dependency changes, the hash changes.
   */
  computeHash(context: ComponentContext): string {
    const files = [
      CACHE_VERSION,
      context.fileContent,
      ...(context.dependencies?.map((d) => d.content) || []),
    ];
    const content = JSON.stringify(files);
    return crypto.createHash("sha256").update(content).digest("hex");
  }

  /**
   * Get a cached entry if it exists and is not expired.
   */
  get(hash: string): CacheEntry | null {
    try {
      const cache = this.readCache();
      const entry = cache[hash];
      if (!entry) return null;

      // Check TTL
      if (Date.now() - entry.timestamp > CACHE_TTL_MS) {
        this.delete(hash);
        return null;
      }

      return entry;
    } catch {
      return null;
    }
  }

  /**
   * Set a cache entry.
   */
  set(hash: string, entry: CacheEntry): void {
    try {
      const cache = this.readCache();
      cache[hash] = entry;

      // Enforce max entries (LRU by timestamp)
      const entries = Object.entries(cache).sort(
        (a, b) => a[1].timestamp - b[1].timestamp,
      );
      if (entries.length > MAX_CACHE_ENTRIES) {
        const toDelete = entries.slice(0, entries.length - MAX_CACHE_ENTRIES);
        for (const [key] of toDelete) {
          delete cache[key];
        }
      }

      this.writeCache(cache);
    } catch (error) {
      console.error("Failed to write cache:", error);
    }
  }

  /**
   * Delete a specific cache entry.
   */
  delete(hash: string): void {
    try {
      const cache = this.readCache();
      delete cache[hash];
      this.writeCache(cache);
    } catch {
      // Ignore
    }
  }

  /**
   * Clear expired entries from the cache.
   */
  clearExpired(): void {
    try {
      const cache = this.readCache();
      const now = Date.now();
      let changed = false;
      for (const [hash, entry] of Object.entries(cache)) {
        if (now - entry.timestamp > CACHE_TTL_MS) {
          delete cache[hash];
          changed = true;
        }
      }
      if (changed) {
        this.writeCache(cache);
      }
    } catch {
      // Ignore
    }
  }

  /**
   * Clear all cache entries.
   */
  clear(): void {
    try {
      this.writeCache({});
    } catch {
      // Ignore
    }
  }

  private readCache(): CacheData {
    if (!fs.existsSync(this.cachePath)) {
      return {};
    }
    try {
      const content = fs.readFileSync(this.cachePath, "utf-8");
      return JSON.parse(content);
    } catch {
      return {};
    }
  }

  private writeCache(cache: CacheData): void {
    const dir = path.dirname(this.cachePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(this.cachePath, JSON.stringify(cache, null, 2));
  }
}